# Config file for air
[build]
bin = "main"
cmd = "go build -o {{.Bin}} {{.Main}}"
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = ["air.toml"]
follow_symlink = true
full_bin = "APP_ENV=dev APP_USER=air {{.Bin}}"
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
color = true
format = "json"
level = "debug"
output = "air.log"
timestamp = true

[serve]
address = "0.0.0.0"
bin = "main"
check_interval = 1
cmd = "APP_ENV=dev APP_USER=air {{.Bin}}"
debug = true
grace_period = 1000
ignore = ["assets", "tmp", "vendor"]
kill_delay = 500
port = 4000
restart = true
shell = "sh"
watch_delay = 200
watch_dir = "."
watch_ext = ["go", "tpl", "tmpl", "html"]
