# Config file for air
[build]
  bin = "main"
  cmd = "go build -o {{.Bin}} {{.Main}}"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = ["air.toml"]
  follow_symlink = true
  full_bin = "APP_ENV=dev APP_USER=air {{.Bin}}"

[log]
  level = "debug"

[serve]
  watch_dir = "."
  watch_ext = ["go", "tpl", "tmpl", "html"]
  watch_delay = 200
  ignore = ["assets", "tmp", "vendor"]
  kill_delay = 500
  grace_period = 1000
  shell = "sh"
  cmd = "APP_ENV=dev APP_USER=air {{.Bin}}"
  bin = "main"
  port = 4000
  address = "0.0.0.0"
  restart = true
  debug = true
  check_interval = 1
  